name: ava
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.4.5
  firebase_ui_auth: ^1.16.0
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png