// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVTWUkr7_QtoqT-a3_Ly8YNXABP26_cfU',
    appId: '1:653745890535:web:2d871f1bc204f671196e42',
    messagingSenderId: '653745890535',
    projectId: 'fir-health-79f9b',
    authDomain: 'fir-health-79f9b.firebaseapp.com',
    storageBucket: 'fir-health-79f9b.firebasestorage.app',
    measurementId: 'G-0FXSLZDFVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9To8FgVTyXTA-aegEGh_XM07EkTYV49o',
    appId: '1:653745890535:android:e431e43bdab0962a196e42',
    messagingSenderId: '653745890535',
    projectId: 'fir-health-79f9b',
    storageBucket: 'fir-health-79f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYz-rGEKFi0EuZMb3G-6AjcWdTbSFH3M',
    appId: '1:653745890535:ios:61fcdedf16b6d23f196e42',
    messagingSenderId: '653745890535',
    projectId: 'fir-health-79f9b',
    storageBucket: 'fir-health-79f9b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYYz-rGEKFi0EuZMb3G-6AjcWdTbSFH3M',
    appId: '1:653745890535:ios:61fcdedf16b6d23f196e42',
    messagingSenderId: '653745890535',
    projectId: 'fir-health-79f9b',
    storageBucket: 'fir-health-79f9b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVTWUkr7_QtoqT-a3_Ly8YNXABP26_cfU',
    appId: '1:653745890535:web:bfbf332d05c13f88196e42',
    messagingSenderId: '653745890535',
    projectId: 'fir-health-79f9b',
    authDomain: 'fir-health-79f9b.firebaseapp.com',
    storageBucket: 'fir-health-79f9b.firebasestorage.app',
    measurementId: 'G-DRVNR16B3M',
  );
}
