// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlqUtj4pTcGzNL16GXEgcE1n22_E6yKx0',
    appId: '1:233893476568:web:faa722222629193d0f3fad',
    messagingSenderId: '233893476568',
    projectId: 'avadb-a6336',
    authDomain: 'avadb-a6336.firebaseapp.com',
    storageBucket: 'avadb-a6336.firebasestorage.app',
    measurementId: 'G-LBDEKNPQ05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc4JXdlzDeCT5OYkyTOTBOQnSH6ln2iX0',
    appId: '1:233893476568:android:b892ed1a3b20359b0f3fad',
    messagingSenderId: '233893476568',
    projectId: 'avadb-a6336',
    storageBucket: 'avadb-a6336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTMG9OCNhPzsKHZw11nimcKYIu5RIOxM',
    appId: '1:233893476568:ios:81aed08a32531ea10f3fad',
    messagingSenderId: '233893476568',
    projectId: 'avadb-a6336',
    storageBucket: 'avadb-a6336.firebasestorage.app',
    iosBundleId: 'com.example.ava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxTMG9OCNhPzsKHZw11nimcKYIu5RIOxM',
    appId: '1:233893476568:ios:81aed08a32531ea10f3fad',
    messagingSenderId: '233893476568',
    projectId: 'avadb-a6336',
    storageBucket: 'avadb-a6336.firebasestorage.app',
    iosBundleId: 'com.example.ava',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlqUtj4pTcGzNL16GXEgcE1n22_E6yKx0',
    appId: '1:233893476568:web:1c3f25ea9c66dc540f3fad',
    messagingSenderId: '233893476568',
    projectId: 'avadb-a6336',
    authDomain: 'avadb-a6336.firebaseapp.com',
    storageBucket: 'avadb-a6336.firebasestorage.app',
    measurementId: 'G-SSZXD01LWL',
  );
}
